[package]
name = "taxi_ride"
version = "0.1.0"
authors = ["Carl Findahl <carlhf@stud.ntnu.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]