name:                tic-tac-roll
version:             0.1.0.0
github:              "githubuser/tic-tac-roll"
license:             MIT
author:              "Mariusz Nowostawski"
maintainer:          "mariusz.nowostawski@ntnu.no"
copyright:           "2021 Mariusz Nowostawski (NTNU)"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tic-tac-roll#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- random
- mtl

library:
  source-dirs: src

executables:
  tic-tac-roll-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tic-tac-roll

tests:
  tic-tac-roll-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tic-tac-roll
    - doctest
